ansible_python_interpreter: /usr/bin/python3

# Credentials
crypt_passphrase: password
unix_username: username
unix_password: password

# Misc
machine_hostname: archlinux-workstation
locale: en_US.UTF-8
timezone: Europe/Paris
# keymap: fr
git_user_name: username
git_user_email: email@domain.com
